// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVFLswPtWAkS8r_56bfMNslcjpnhr-YzE',
    appId: '1:967831759023:web:6af2dd74807033f7cf4c5a',
    messagingSenderId: '967831759023',
    projectId: 'blog-task-e717e',
    authDomain: 'blog-task-e717e.firebaseapp.com',
    storageBucket: 'blog-task-e717e.appspot.com',
    measurementId: 'G-LQ0DKQPD06',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOJ6kYoYzYYkBy_hgqATvsffXOwVrcoAM',
    appId: '1:967831759023:android:ae302f2d2d628544cf4c5a',
    messagingSenderId: '967831759023',
    projectId: 'blog-task-e717e',
    storageBucket: 'blog-task-e717e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-36WzixT-Yt06pCCJdUsEGq4GCKOEmf8',
    appId: '1:967831759023:ios:88b717d88440edfbcf4c5a',
    messagingSenderId: '967831759023',
    projectId: 'blog-task-e717e',
    storageBucket: 'blog-task-e717e.appspot.com',
    iosClientId: '967831759023-6tshmmp554nao2pf8b27he1lhtva6rrr.apps.googleusercontent.com',
    iosBundleId: 'com.example.blogTask',
  );
}
